name: vprofile-app

services:
  backend:
    build:
      context: app
      dockerfile: Dockerfile

    networks:
      - backend-network
      - reverse-proxy-network

    depends_on:
      - database
      - cache
      - message-broker

  database:
    image: mariadb:12.0.2-ubi
    env_file:
      - config/db/.env

    volumes:
      - type: bind
        source: config/db/init.sql
        target: /docker-entrypoint-initdb.d/init.sql
        read_only: true

      - type: volume
        source: database-volume
        target: /var/lib/mysql

    networks:
      - backend-network

  cache:
    image: memcached:alpine3.22
    networks:
      - backend-network

  message-broker:
    image: rabbitmq:4.1.4-alpine
    env_file:
      - config/message-broker/.env

    networks:
      - backend-network

  reverse-proxy:
    image: nginx:alpine3.22
    volumes:
      - type: bind
        source: config/reverse-proxy/nginx.conf
        target: /etc/nginx/conf.d/default.conf

    networks:
      - reverse-proxy-network

    ports:
      - "80:80"

    depends_on:
      - backend

networks:
  backend-network:
    driver: bridge
  reverse-proxy-network:
    driver: bridge

volumes:
  database-volume:
    driver: local
